source "https://rubygems.org"
gem "guard", "= 1.8.1"
  gem "guard-bundler"
  gem "guard-rspec"
  gem 'guard-spork', :git => "git://github.com/rubycut/guard-spork.git", :branch => "no_empty_env_merge"
  gem "guard-cucumber"
  gem 'rack-livereload'
  gem "guard-livereload"
  #gem "rb-inotify"
  gem "spork"
  gem "guard-shell"
  gem "guard-rack"
  # for better pry guard integration
  # gem "rb-readline"
  gem "rspec"
